theme = "docuapi"
languageCode = "en-us"
baseurl = "https://docs.ito-app.org"
title = "DocuAPI Example Site"

disableKinds = ["taxonomyTerm"]

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = false

defaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"

[module]
[module.hugoVersion]
[[module.imports]]
# We include the theme by "../.." above, but we need one module import for Hugo to detect us as a Hugo Module.
path="github.com/bep/empty-hugo-module"

[params]
search = true
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "go"
name = "Go" 
[[params.language_tabs]]
key = "java"
name = "Java"

#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "ito API documentation"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='https://github.com/ito-org/documentation'>Edit on Github</a>",
"Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme by [bep](https://github.com/bep)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true


#[languages.nn]
#languageName = "Nynorsk"
#weight = 1
#title = "DocuAPI-døme"

# Left sidebar footer items. Use HTMl or Markdown.
#toc_footers = [ 
#"<a href='#'>Registrer deg for ein utviklarnøkkel</a>",
#"Dokumentasjonen er driven av [DocuAPI](https://github.com/bep/docuapi)",
#"Hugo Theme av [bep](https://github.com/bep)"
#]

[languages.nn.blackfriday]
# Norwegian uses angled quotes
#angledQuotes = true
#hrefTargetBlank = true
